pipeline {
    agent any

    stages {
        
        steps {
        
             docker { image 'maven:3-alpine'
                 args '-v /root/.m2:/root/.m2'
               }
           
        }
        
        
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
